name: Test `env-label` Action

on:
  push:
    branches:
      - main

permissions: 
  contents: write
  pull-requests: write
  
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Random Branch Name
        id: random_branch
        run: |
          echo "BASE_BRANCH=base-$(openssl rand -hex 4)" >> $GITHUB_ENV
          echo "HEAD_BRANCH=head-$(openssl rand -hex 4)" >> $GITHUB_ENV

      - name: Git configuration
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "xctions@users.noreply.github.com"

      - name: Create base branch
        run: |
          base_branch=$(echo ${{ env.BASE_BRANCH }})
          git checkout -b $base_branch
          git push origin $base_branch

      - name: Create head branch
        run: |
          HEAD_BRANCH="head-$(openssl rand -hex 4)"
          git checkout -b $HEAD_BRANCH
          echo "Some minor changes" >> README.md
          git add README.md
          git commit -m "Minor changes"
          git push origin $HEAD_BRANCH

      - name: Create pull request
        id: create_pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          echo ================================================
          git branch -a
          echo ================================================
          pr_url=$(gh pr create --base $base_branch --head $head_branch --title "Test PR" --body "This is a test PR")
          echo "pr_url=$pr_url" >> $GITHUB_OUTPUT

      - name: Add label to PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_number=$(gh pr view ${{ steps.create_pr.outputs.pr_url }} --json number --jq '.number')
          gh pr edit $pr_number --add-label "dev"

      - name: Run `env-label` action
        uses: ./.github/actions/env-label
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ steps.create_pr.outputs.pr_number }}
          repository: ${{ github.repository }}