name: Test `env-label` Action

on:
  push:
    branches:
      - main

permissions: 
  contents: write
  pull-requests: write
  
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create base branch
        run: |
          base_branch="base-$(openssl rand -hex 4)"
          git checkout -b $base_branch
          git push origin $base_branch

      - name: Create head branch
        run: |
          head_branch="head-$(openssl rand -hex 4)"
          git checkout -b $head_branch
          echo "Some minor changes" >> README.md
          git add README.md
          git commit -m "Minor changes"
          git push origin $head_branch

      - name: Create pull request
        id: create_pr
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_url=$(gh pr create --base $base_branch --head $head_branch --title "Test PR" --body "This is a test PR")
          echo "pr_url=$pr_url" >> $GITHUB_ENV

      - name: Add label to PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          pr_number=$(gh pr view ${{ env.pr_url }} --json number --jq '.number')
          gh pr edit $pr_number --add-label "dev"

      - name: Run `env-label` action
        uses: ./.github/actions/env-label
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ steps.create_pr.outputs.pr_number }}
          repository: ${{ github.repository }}